# Generated by Django 3.2 on 2022-04-15 07:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='used_time',
            field=models.DateTimeField(
                blank=True,
                default=account.models.used_timedelta,
                null=True,
                verbose_name='Used Time'),
        ),
    ]
